print()
print('4.5 – Somando um milhão:\n Crie uma lista de números de um a um milhão e, em seguida, use min() e max() para garantir que sua lista realmente começa em um e termina em um milhão. Além disso, utilize a função sum() para ver a rapidez com que Python é capaz de somar um milhão de números.')
print()
numero = list(range(1,1000001))
print(numero)
print('DADOS DA LISTA:')
print('Menor número da lista: ',min(numero))
print('Maior número da lista: ',max(numero))
print('A soma dos números da lista: ',sum(numero))