print()
print('4.7– Três:\n Crie uma lista de múltiplos de 3, de 3 a 30. Use um laço for para exibir os números de sua lista.')
print()
tres = list(range(3,33,3))
print('Os números multiplos de 03 da lista: ',tres)